package cn.threefishes.cloudrepository.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;


import java.util.List;

@Repository
@Mapper
public interface GeneralMyBatisMapper<T, E>  {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    long countByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    int deleteByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    List<T> selectByExample(E example);

    T

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    int updateByExample(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table album
     *
     * @mbg.generated Sat Jun 01 21:38:49 GMT+08:00 2019
     */
    int updateByPrimaryKey(T record);


    List<T> selectByExampleWithRowbounds(E example, RowBounds rowBounds);


}
