spring:
  application:
    name: tfcloud-mainapi
  redis:
    database: 0

    host: 127.0.0.1

    port: 6379
    password:
    timeout: 30000
    block-when-exhausted: true
    jedis:
      pool:
        max-active: 32
        max-wait: 300
        max-idle: 16
        min-idle: 4
  redispre:
    value: "t:cache:"
  tokenpre:
    value: "token:"
  sessionpre:
    value: "session:"
  session:
    store-type: redis
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

hikari:
  master:
    jdbc-url: jdbc:mysql://127.0.0.1/qtf?characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: collec

    maximum-pool-size: 20
    pool-name: master
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
  slave:
    jdbc-url: jdbc:mysql://127.0.0.1/qtf?characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: collec
    maximum-pool-size: 20
    pool-name: master
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    
aliyun:
  oss:
    accessId:   sdafdsdfsFDGDFGDF
    accessKey:  FDGDFGDFGDFGD
    bucket:      WERWERWERWE
    endpoint:    oss-cn-beijing.aliyuncs.com
    uploadOpen: true
    uploadRoot: https://w.threefishes.cn/
    gyyUploadRoot: https://12132123.oss-cn-zhangjiakou.aliyuncs.com/

#微信配置
weChat:
  red:
    ip: 123.123.123.123
  #小程序
  mini:
    #小程序 appId
    appId: wxcb4534534534534534534
    #小程序 appSecret
    secret: 434534534534534534534534534534
    #授权类型，此处只需填写 authorization_code
    grantType: authorization_code
    #小程序域名
    urlHost: https://w.threefishes.cn/
    #URL TOKEN
    urlToken: ssertertw4e5w345tre
  #公众号
  official:
    #公众号appid
    appId: wx84324234234234234
    #微信公众号appSecret
    secret: werwerwreser23423423453245345
    #URL TOKEN
    urlToken: threefishes,djfslkdfj
  #商户号
  merchant:
    #商户号
    merchantId: 12312312312
    #商户key
    merchantKey: 1242342342312312312312312
    #支付成功回调地址前缀
    notifyUrlPre: https://w.threefishes.cn/service/

#管易云配置
GYY:
  appkey: 1tyrtyrt
  sessionkey: 3523452452435435345
  secret: etertertertert
  url: http://api.guanyierp.com/rest/erp_open
  shopCode: retertsrg
  warehouse: terterterter

# 工猫提现配置
real:
   wapurl: https://contract-qa01.gongmall.com/url_contract.html
   apiurl: https://openapi-qa.gongmall.com
   appkey: werwerwerwer
   appsecret: wrewerwerwerwer
   companyid: rwerwerwe
   positionid: rewerwerw
   realnumber: erwerwerwer

task:
  wechat:
    flush:
          #每小时刷新token
      cron: 0 0 0 29 2 ?